### PR TITLE
feat(deps): update md5 dependecie

### PR DESCRIPTION
**Pull request by jpsc**
Seems to work but since there is no tests can't be 100% sure :)

### CODE REVIEW

**Comment by jpsc** [comment]
@ArjBasu can you look into merging this or not ? 👍

**Comment by ArjBasu** [comment]
@jpsc Sorry I missed the thread completely. Will look into it.

**Comment by jpsc** [comment]
Thanks 👍

**Comment by jpsc** [comment]
Can you release this to npm?
Still pointing to old version :)

**Pull request merged**
